config/routes.rb
Rails.application.routes.draw do

  resources :closures

  resources :sessions
  get 'welcome/index'

  get 'login' => 'sessions#new', as: :login
  get 'logout' => 'sessions#destroy', as: :logout

  get 'check_pdf' => 'welcome#check_pending_pdf'
  get 'download' => 'welcome#download'
  

  post 'create_admin_user' => 'welcome#create_admin_user', as: :create_admin_user
  get 'admin_user' => 'welcome#admin_user', as: :administrator_user
  

  

  get 'admin' => 'welcome#admin', as: :admin_index
  get 'owner' => 'welcome#owner', as: :owner_index
  get 'seller' => 'welcome#seller', as: :seller_index

  root 'welcome#index'

  get 'my_profile' => 'users#my_profile', as: :my_profile
  namespace "admin" do
    resources :users
    resources :roles
    resources :commerces
    resources :stores
    resources :deposits
    resources :sellers
    resources :downloads
    resources :loads
  end
  
 
  namespace "owner" do
    resources :users
    resources :commerces do
      resources :deposits, :stores,:sellers
      get 'deposits/:id/products' => 'deposits#products', as: :deposit_products
      get 'deposits/:id/products/new' => 'deposits#new_product', as: :new_deposit_product
      get 'deposits/:deposit_id/products/:product_id' => 'deposits#show_product', as: :deposit_product
      post 'deposits/:deposit_id/products' => 'deposits#add_product'
      get 'deposits/:deposit_id/products/:product_id/edit' => 'deposits#edit_product', as: :edit_deposit_product
      patch 'deposits/:deposit_id/products/:product_id' => 'deposits#update_product' 
      put 'deposits/:deposit_id/products/:product_id' => 'deposits#update_product' 
      
      get 'stores/:store_id/products' => 'stores#products', as: :store_products
      get 'stores/:store_id/products/new' => 'stores#new_product', as: :new_store_product
      get 'stores/:store_id/products/:product_id' => 'stores#show_product', as: :store_product 
      post 'stores/:store_id/products' => 'stores#add_product'
      get 'stores/:store_id/products/:id/edit' => 'stores#edit_product', as: :edit_store_product
      patch 'stores/:store_id/products/:id' => 'stores#update_product' 
      put 'stores/:store_id/products/:id' => 'stores#update_product' 
      get 'stores/:store_id/close_cash' => 'stores#close_cash', as: :close_cash
      
    end
    resources :loads
    resources :downloads
    resources :sales
    resources :bills
  end
  
  namespace "seller" do
    resources :users
    get 'store/products' => 'stores#products', as: :store_products
    get 'store' => 'stores#show', as: :store
    get 'store/close_cash' => 'stores#close_cash', as: :close_cash
      
    resources :sales
    resources :bills

  end
    resources :users
    resources :products
    resources :categories
    resources :brands
    resources :units

end

app/models/seller.rb
class Seller < ActiveRecord::Base
  belongs_to :user
  belongs_to :commerce
  belongs_to :store
  has_many :bills
  has_many :closures
  accepts_nested_attributes_for :user, allow_destroy: true

  extend FriendlyId
  friendly_id :identifier, use: :slugged

  def identifier
  	self.user.cedula
  end
  def nombre_comercio
  		self.commerce	 ? self.commerce.nombre : "S/C"
 	end
end

app/controllers/admin/sellers_controller.rb
class SellersController < ApplicationController
  before_action :set_seller, only: [:show, :edit, :update, :destroy]
  before_action :verify_owner_role, only: [:create,:update]

  # GET /sellers
  # GET /sellers.json
  def index
    if current_user.admin?
      @sellers = Seller.all
    end
    if current_user.owner?
     @sellers=current_user.commerces.friendly.find(get_commerce(params[:commerce_id])).sellers
    end
  end

  # GET /sellers/1
  # GET /sellers/1.json
  def show
  end

  # GET /sellers/new
  def new
    if current_user.admin?
      @seller = Seller.new
    end
    if current_user.owner?
        @commerce = get_commerce(params[:commerce_id])
        @seller = Seller.new
        @seller.commerce_id = @commerce.id
    end
  end
  # GET /commerce/:commerce_id/sellers/new

  # GET /sellers/1/edit
  def edit
    if current_user.owner?
      @commerce = get_commerce(params[:commerce_id])
    end
  end

  # POST /sellers
  # POST /sellers.json
  def create
    @seller = Seller.new(seller_params)

    respond_to do |format|
      if @seller.save
        ruta = current_user.admin? ? sellers_path : sellers_of_commerce_path(@seller.commerce.slug)
        format.html { redirect_to ruta, notice: 'Seller was successfully created.' }
        format.json { render :show, status: :created, location: @seller }
      else
        format.html { render :new }
        format.json { render json: @seller.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sellers/1
  # PATCH/PUT /sellers/1.json
  def update
    respond_to do |format|
      if @seller.update(seller_params)
        ruta = current_user.admin? ? sellers_path : sellers_of_commerce_path(@seller.commerce.slug)
        format.html { redirect_to ruta, notice: 'Seller was successfully updated.' }
        format.json { render :show, status: :ok, location: @seller }
      else
        format.html { render :edit }
        format.json { render json: @seller.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sellers/1
  # DELETE /sellers/1.json
  def destroy
    @seller.destroy
    respond_to do |format|
      format.html { redirect_to sellers_url, notice: 'Seller was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_seller
      @seller = Seller.find(params[:id])
    end
    def verify_owner_role
      if current_user.owner?
        params[:seller][:user_attributes][:role_id]= seller_role
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def seller_params
      params.require(:seller).permit(:commerce_id, :store_id,
      user_attributes: [:id, :cedula, :password, :password_confirmation, :role_id,:_destroy,
      profile_attributes: [:id,:primer_nombre, :segundo_nombre, :primer_apellido, :segundo_apellido, :sexo, :email, :celular, :_destroy]
      ])
    end


    def user_params
      params.require(:user).permit(:cedula, :password, :password_confirmation, :role_id, profile_attributes: [:id,:primer_nombre, :segundo_nombre, :primer_apellido, :segundo_apellido, :sexo, :email, :celular, :_destroy])
    end

end

app/controllers/owner/sellers_controller.rb
class Owner::SellersController < ApplicationController
  before_action :set_commerce
  before_action :set_seller, only: [:show, :edit, :update, :destroy]

  # GET /sellers
  # GET /sellers.json
  def index
    @sellers = @commerce.sellers
  end

  # GET /sellers/1
  # GET /sellers/1.json
  def show
  end

  # GET /sellers/new
  def new
    commerce = current_user.commerces.friendly.find(params[:commerce_id])

    puts "Cantidad de tiendas::"+commerce.stores.count.to_s
    if  commerce.stores.count == 0
        redirect_to(:back,alert: "Disculpa, este comercio no posee tiendas para agregar un vendedor")
    end
    @seller = Seller.new
  end

  # GET /sellers/1/edit
  def edit
  end

  # POST /sellers
  # POST /sellers.json
  def create
    @seller = Seller.new(seller_params)
    @seller.commerce = @commerce
    @seller.user.role_id = seller_role
    respond_to do |format|
      if @seller.save
        format.html { redirect_to owner_commerce_sellers_path(@seller.commerce.slug), notice: 'Vendedor creado exitosamente.' }
        format.json { render :show, status: :created, location: @seller }
      else
        format.html { render :new }
        format.json { render json: @seller.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sellers/1
  # PATCH/PUT /sellers/1.json
  def update
    respond_to do |format|
      @seller.slug=nil
      if @seller.update(seller_params)
        format.html { redirect_to owner_commerce_sellers_path(@seller.commerce.slug), notice: 'Vendedor actualizado exitosamente.' }
        format.json { render :show, status: :ok, location: @seller }
      else
        format.html { render :edit }
        format.json { render json: @seller.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sellers/1
  # DELETE /sellers/1.json
  def destroy
    @seller.destroy
    respond_to do |format|
      format.html { redirect_to sellers_url, notice: 'Seller was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_seller
      @seller = @commerce.sellers.friendly.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def seller_params
      params.require(:seller).permit(:commerce_id, :store_id,
      user_attributes: [:id, :cedula, :password, :password_confirmation, :role_id,:_destroy,
      profile_attributes: [:id,:primer_nombre, :segundo_nombre, :primer_apellido, :segundo_apellido, :sexo, :email, :celular, :_destroy]
      ])
    end

end

app/controllers/seller/bills_controller.rb
class Seller::BillsController < ApplicationController
  before_action :set_bill, only: [:show, :edit, :update, :destroy]
  after_action :set_date_created_at, only: [:create]
  after_action :set_date_updated_at, only: [:update]
  # GET /bills
  # GET /bills.json
  def index
    @bills = Bill.all
  end

  # GET /bills/1
  # GET /bills/1.json
  def show
  end

  # GET /bills/new
  def new
    @bill = Bill.new
  end

  # GET /bills/1/edit
  def edit
  end

  # POST /bills
  # POST /bills.json
  def create
    @bill = Bill.new(bill_params)
    @bill.seller = current_user.sellers.first
    sales = params[:sales]
    @bill.cantidad_total = sales.sum(:cantidad)
 
    respond_to do |format|
      if @bill.save
        sales.each do |i, sale|
          puts "AQUIVALE"
          puts sale.to_json
          new_sale=Sale.new
          new_sale.product_id=sale["id"].to_i
          new_sale.cantidad=sale["cantidad"].to_i
          new_sale.precio=sale["precio"].to_f
          new_sale.bill=@bill
          
          downloads = @bill.seller.store.downloads.where(product_id: new_sale.product_id)
          if downloads.sum(:cantidad)<new_sale.cantidad
            puts "Error"
          else
            cantidad_cargada=new_sale.cantidad
            downloads.order(:created_at).each do |download|
            if cantidad_cargada==0 and download.cantidad!=0
              break;
            else
              if download.cantidad>=cantidad_cargada
                download.cantidad=download.cantidad-cantidad_cargada
                download.save
                break;
              else
                cantidad_cargada=cantidad_cargada-download.cantidad
                download.cantidad=0
                download.save
                end  
              end
            end
            puts "todo ok"
          end
          new_sale.save
        end
        @commerce = @bill.seller.commerce
        @store = @bill.seller.store 
        format.html { redirect_to root_path, notice: 'Bill was successfully created.' }
        format.json { render :show, status: :created, location: root_path }
      else
        format.html { render :new }
        format.json { render json: @bill.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bills/1
  # PATCH/PUT /bills/1.json
  def update
    respond_to do |format|
      if @bill.update(bill_params)
        format.html { redirect_to @bill, notice: 'Bill was successfully updated.' }
        format.json { render :show, status: :ok, location: @bill }
      else
        format.html { render :edit }
        format.json { render json: @bill.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bills/1
  # DELETE /bills/1.json
  def destroy
    @bill.destroy
    respond_to do |format|
      format.html { redirect_to bills_url, notice: 'Bill was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_date_created_at
      if params[:fecha]
        puts "Se informo la fecha desde el cliente::"+params[:fecha]
        f = JSON.parse(params[:fecha])
        fecha = DateTime.new(f["anio"], f["mes"], f["dia"],  f["hora"],  f["min"],  f["seg"])
      end
      time = getCurrentTime
      puts "Respondio el webservice del tiempo::"+time.to_s
        
      @bill.created_at = time ? time : (fecha ? fecha : Date.today)
      @bill.updated_at = time ? time : (fecha ? fecha : Date.today)
      @bill.save
    end
    def set_date_updated_at
      if params[:fecha]
        f = JSON.parse(params[:fecha])
        fecha = DateTime.new(f["anio"], f["mes"], f["dia"],  f["hora"],  f["min"],  f["seg"])
      end
      time = getCurrentTime
      puts @fecha.to_s
      @bill.updated_at = time ? time : (fecha ? fecha : Date.today)
      @bill.save
    end 
    def set_bill
      @bill = Bill.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def bill_params
      params.require(:bill).permit(:total)
    end
end

app/controllers/seller/sales_controller.rb
class Seller::SalesController < ApplicationController
  before_action :set_sale, only: [:show, :edit, :update, :destroy]

  # GET /sales
  # GET /sales.json
  def index
    @sales = Sale.all
  end

  # GET /sales/1
  # GET /sales/1.json
  def show
  end

  # GET /sales/new
  def new
    @sale = Sale.new
  end

  # GET /sales/1/edit
  def edit
  end

  # POST /sales
  # POST /sales.json
  def create
    @sale = Sale.new(sale_params)

    respond_to do |format|
      if @sale.save
        format.html { redirect_to @sale, notice: 'Sale was successfully created.' }
        format.json { render :show, status: :created, location: @sale }
      else
        format.html { render :new }
        format.json { render json: @sale.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sales/1
  # PATCH/PUT /sales/1.json
  def update
    respond_to do |format|
      if @sale.update(sale_params)
        format.html { redirect_to @sale, notice: 'Sale was successfully updated.' }
        format.json { render :show, status: :ok, location: @sale }
      else
        format.html { render :edit }
        format.json { render json: @sale.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sales/1
  # DELETE /sales/1.json
  def destroy
    @sale.destroy
    respond_to do |format|
      format.html { redirect_to sales_url, notice: 'Sale was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sale
      @sale = Sale.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def sale_params
      params.require(:sale).permit(:cantidad, :precio)
    end
end

app/controllers/seller/users_controller.rb
class Seller::UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

 # before_action :validate_password, only:[:create]
  # GET /users_url
  # GET /users.json
  def index
    if current_user.admin?
      @users = User.all
    end
  
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
    puts "++++"+@user.crypted_password
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)
    respond_to do |format|
      if @user.save
        format.html { redirect_to users_path, notice: 'Usuario creado exitosamente.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      @user.slug=nil
      if @user.update(user_params)
        ruta = @user==current_user ? root_path : users_path
        format.html { redirect_to ruta, notice: 'Usuario actualizado exitosamente.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

 def my_profile
    @user = current_user
    render 'edit'
  end
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = current_user
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:cedula, :password, :password_confirmation, :role_id, profile_attributes: [:id,:primer_nombre, :segundo_nombre, :primer_apellido, :segundo_apellido, :sexo, :email, :celular, :_destroy])
    end

end

app/helpers/sellers_helper.rb
module SellersHelper
end

app/views/sellers/_form.html.erb
<%= form_for(setup_seller(@seller)) do |seller_field| %>
  <%= seller_field.fields_for :user do |user_field| %>
      <%= user_field.fields_for :profile, @seller.user.profile  do |profile_field| %>

  <script type="text/javascript">
   var errorsArray=[] ;
  <% @seller.errors.each do |atributo, mensaje| %>
      errorsArray.push({atributo:"<%="#{atributo}"%>",mensaje:"<%="#{mensaje}"%>"});
  <% end %>
  $( document ).ready(function() {
    validarErrores(errorsArray);
  });
</script>
  <div class="box box-primary">
    <div class="box-header with-border">
      <h3 class="box-title">Datos Personales</h3>
    </div><!-- /.box-header -->

    <div class="box-body">
      
        <div class="row">
        <div class="col-xs-12 col-sm-6 col-md-6 col-lg-6">
          <div class="form-group">
              <%= user_field.label :cedula %>*<br>
              <%= user_field.text_field :cedula, type:"number",class:"form-control cedula",required: true,data:{
                maxlength: "11"
                } %>
             </div>
          </div>
          <div class="col-xs-12 col-sm-6 col-md-6 col-lg-6">
            <div class="form-group">
              <%= profile_field.label :sexo %>*<br>
              <%= profile_field.radio_button:sexo,'true', :checked => true %>
              Masculino              
              <%= profile_field.radio_button:sexo,'false', :checked => false %>
              Femenino
            </div>
          </div>        
        </div>
        <div class="row">
          <div class="col-xs-12 col-sm-6 col-md-6 col-lg-6">
            <div class="form-group">
              <%= profile_field.label :primer_nombre %>*<br>
              <%= profile_field.text_field :primer_nombre,class:"form-control" %>
            </div>
          </div>
          <div class="col-xs-12 col-sm-6 col-md-6 col-lg-6">
            <div class="form-group">
              <div class="form-group">
                <%= profile_field.label :segundo_nombre %><br>
                <%= profile_field.text_field :segundo_nombre,class:"form-control"  %>
              </div>
            </div>
          </div>
        </div>
        <div class="row">
          <div class="col-xs-12 col-sm-6 col-md-6 col-lg-6">
            <div class="form-group">
              <%= profile_field.label :primer_apellido %>*<br>
              <%= profile_field.text_field :primer_apellido,class:"form-control" %>
            </div>
          </div>
          <div class="col-xs-12 col-sm-6 col-md-6 col-lg-6">
            <div class="form-group">
              <div class="form-group">
                <%= profile_field.label :segundo_apellido %><br>
                <%= profile_field.text_field :segundo_apellido,class:"form-control"  %>
              </div>
            </div>
          </div>
        </div>
        <div class="row">
          <div class="col-xs-12 col-sm-6 col-md-6 col-lg-6">
            <div class="form-group">
            <%= profile_field.label :email %><br>
              <div class="input-group">
                <span class="input-group-addon"><i class="fa fa-envelope"></i></span>
                <%= profile_field.email_field :email,class:"form-control", placeholder: "Email"%>
              </div>
            </div>
          </div>
          <div class="col-xs-12 col-sm-6 col-md-6 col-lg-6">
            <div class="form-group">
              <%= profile_field.label :celular %><br>
              <div class="input-group">
                <div class="input-group-addon">
                  <i class="fa fa-phone"></i>
                </div>
                <%= profile_field.text_field :celular,class:"form-control", "data-inputmask" => '"mask": "(9999) 999-9999"'  %>
              </div><!-- /.input group -->
            </div>
          </div>
        </div>
    </div><!-- /.box-body -->
  </div><!-- /.box -->
  <%if !@seller.user.persisted?%>
    <div class="box box-primary">
      <div class="box-header with-border">
        <h3 class="box-title">Contraseña de ingreso</h3>
      </div><!-- /.box-header -->
      <div class="box-body">
        <div class="row">
          <div class="col-xs-12 col-sm-6 col-md-6 col-lg-6">
            <div class="form-group">
              <%= user_field.label :password, "Contraseña"%>*<br>
              <%= user_field.password_field :password,class:"form-control"  %>
            </div>
          </div>
          <div class="col-xs-12 col-sm-6 col-md-6 col-lg-6">
            <div class="form-group">
               <%= user_field.label :password_confirmation, "Confirmar contraseña" %><br />
               <%= user_field.password_field :password_confirmation,class:"form-control" %>
             </div>
          </div>
        </div>
        <%if current_user.admin?%>
          <div class="row">
            <div class="col-xs-12 col-sm-6 col-md-6 col-lg-6">
              <div class="form-group">
                <%= user_field.label :role_id, "Rol del usuario" %>*<br>
              <%= user_field.select :role_id, options_for_select(Role.all.pluck(:nombre,:id),( @seller.user.role ? @seller.user.role_id : "" )),{},{class:"form-control select2"}%>
              </div>
            </div>
          </div>
        <%end%>
      </div>
    </div><!-- /.box -->
  <%end%>
  <div class="box box-primary">
    <div class="box-header with-border">
      <h3 class="box-title">Datos de la Tienda</h3>
    </div><!-- /.box-header -->

    <div class="box-body">
      <div class="row">
        <div class="col-xs-12 col-sm-6 col-md-6 col-lg-6">
          <div class="form-group">
            <%= seller_field.label :commerce_id, "Comercio asociado" %><br>

            <%if current_user.admin?%>
              <%= seller_field.select :commerce_id, options_for_select(Commerce.all.pluck(:nombre,:id),( @seller.commerce ? @seller.commerce_id : "" )),{},{class:"form-control select2"}%>
            <%end%>

            <%if @commerce!=nil %>
              <%=@commerce.nombre%>
              <%= seller_field.text_field :commerce_id,class:"form-control",type: "hidden" %>
            <%end%>
            
          </div>
        </div>
      </div>
      <div class="row">
        <div class="col-xs-12 col-sm-6 col-md-6 col-lg-6">
          <div class="form-group">
            <%= seller_field.label :store_id, "Tienda asignada" %>*<br>
            <%= seller_field.select :store_id, options_for_select(Store.all.pluck(:nombre,:id),( @seller.store ? @seller.store_id : "" )),{},{class:"form-control select2"}%>
          </div>
        </div>
      </div>


    </div><!-- /.box-body -->
  </div><!-- /.box -->



  
    <div class="box-footer">
      <%= seller_field.submit "Guardar", class: "visible-xs btn btn-block btn-primary btn-lg" %>
      <%= seller_field.submit "Guardar", class: "hidden-xs btn btn-primary" %>
    </div>

    <% end %><!-- /profile_form-->
  <%end%><!-- /user_form-->
<%end%><!-- /seller_field _form-->


<script>
      $(function () {
        //Initialize Select2 Elements
          $("#seller_user_attributes_profile_attributes_celular").inputmask();
          $('input[type="radio"]').iCheck({
          checkboxClass: 'icheckbox_minimal-blue',
          radioClass: 'iradio_minimal-blue'
        });
          $('input[type="radio"]').first().parent().addClass("checked")
          $(".select2").select2();
      });
</script>

app/views/sellers/_sellers_table.html.erb
          <div class="row">
            <div class="col-xs-12">


              <div class="box">
                <div class="box-header">
                  <h3 class="box-title">Lista de Vendedores<%=@commerce ? " de "+@commerce.nombre : "" %></h3>
                </div><!-- /.box-header -->
                <div class="box-body">
                  <table id="sellers_table" class="display table table-bordered table-striped" cellspacing="0" width="100%">
                    <thead>
                      <tr>
                        <th>Nombre</th>
                        <%if current_user.admin?%>
                          <th>Comercio</th>
                        <%end%>
                        <th>Tienda</th>
                      </tr>
                    </thead>
                    <tbody>
                    <% @sellers.each_with_index do |seller,index| %>
                      <tr class="link" data-toggle="modal" data-target=<%="#modal-seller-"+index.to_s%>>
                        <td><%= seller.user.profile.short_name%></td>
                        <%if current_user.admin?%>
                          <td><%= seller.commerce.nombre %></td>
                        <%end%>
                        <td><%= seller.store.nombre %></td>
                      </tr>
                        <div class="example-modal">
                          <div class="modal fade" id=<%="modal-seller-"+index.to_s%>>
                            <div class="modal-dialog">
                              <div class="modal-content">
                                <div class="modal-header">
                                  <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                                  <h4 class="modal-title">Información</h4>
                                </div>
                                <div class="modal-body">
                                  <div class="row">
                                    <div class="col-xs-12">
                                      <div class="box box-solid">
                                        <div class="box-header with-border">
                                          <i class="fa fa-text-width"></i>
                                          <h3 class="box-title">Datos del sellero</h3>
                                        </div><!-- /.box-header -->
                                        <div class="box-body">
                                          <dl>
                                            <dt>Nombre:</dt>
                                            <dd><%=seller.user.profile.short_name%></dd>
                                            <%if current_user.admin?%>
                                              <dt>Comercio:</dt>
                                              <dd><%=seller.commerce.nombre%></dd>
                                            <%end%>
                                            <dt>Tienda:</dt>
                                            <dd><%=seller.store.nombre%></dd>
                                                                                
                                          </dl>
                                       </div><!-- /.box-body -->
                                      </div><!-- /.box -->
                                    </div><!-- ./col -->
                                  </div><!-- /.row -->
                                </div>
                                <div class="modal-footer">
                                  <button type="button" class="btn btn-default pull-left" data-dismiss="modal">Cerrar</button>
                                  
                                  <button data-url=<%=sellers_path%> data-id=<%=seller.id%> type="button" class="btn btn-danger delete-record">Eliminar</button>
                                  <button type="button" class="btn btn-primary" aria-label="Left Align" onclick="window.location.href='<%=current_user.admin? ? edit_seller_path(seller) : edit_seller_of_commerce_path(@commerce.slug,seller) %>'">
                                    <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span> Editar &nbsp;
                                  </button>
                                </div>
                              </div><!-- /.modal-content -->
                            </div><!-- /.modal-dialog -->
                          </div><!-- /.modal -->
                        </div><!-- /.example-modal -->
                      <% end %>
                    </tbody>
                    <tfoot>
                      <tr>
                        <th>Nombre</th>
                        <%if current_user.admin?%>
                          <th>Comercio</th>
                        <%end%>
                        <th>Tienda</th>
                      </tr>
                    </tfoot>
                  </table>
                </div><!-- /.box-body -->
              </div><!-- /.box -->
            </div><!-- /.col -->
          </div><!-- /.row -->

app/views/sellers/index.html.erb
       <!-- Main content -->
        <section class="content">
          <%= render 'sellers_table' %>
        </section><!-- /.content -->


 <script>
      $(function () {
        $("#sellers_table").DataTable({
          "language": {
            "url": "/plugins/datatables/dataTables.spanish.lang"
          },
          "columnDefs": [ {
          "targets": 'no-sort',
          "orderable": false,
          "searchable": false
          } ],
          stateSave: true
        });
      });
</script>
<br>


<div class="row">
    <div class="col-xs-1 col-sm-0"> </div>
    <div class="col-xs-10 col-sm-12"> 

<%= link_to 'Nuevo  Vendedor', current_user.admin? ? new_seller_path : new_seller_of_commerce_path(@commerce) ,class:"visible-xs btn btn-block btn-primary btn-lg"%>
<%= link_to 'Nuevo  Vendedor', current_user.admin? ? new_seller_path : new_seller_of_commerce_path(@commerce) ,class:"hidden-xs btn btn-primary "%>
    </div>
    <div class="col-xs-1 col-sm-0"> </div>

</div> 

app/views/sellers/new.html.erb
<h1>Nuevo Vendedor</h1>

<%= render 'form' %>