config/routes.rb
Rails.application.routes.draw do

  resources :closures

  resources :sessions
  get 'welcome/index'

  get 'login' => 'sessions#new', as: :login
  get 'logout' => 'sessions#destroy', as: :logout

  get 'check_pdf' => 'welcome#check_pending_pdf'
  get 'download' => 'welcome#download'
  

  post 'create_admin_user' => 'welcome#create_admin_user', as: :create_admin_user
  get 'admin_user' => 'welcome#admin_user', as: :administrator_user
  

  

  get 'admin' => 'welcome#admin', as: :admin_index
  get 'owner' => 'welcome#owner', as: :owner_index
  get 'seller' => 'welcome#seller', as: :seller_index

  root 'welcome#index'

  get 'my_profile' => 'users#my_profile', as: :my_profile
  namespace "admin" do
    resources :users
    resources :roles
    resources :commerces
    resources :stores
    resources :deposits
    resources :sellers
    resources :downloads
    resources :loads
  end
  
 
  namespace "owner" do
    resources :users
    resources :commerces do
      resources :deposits, :stores,:sellers
      get 'deposits/:id/products' => 'deposits#products', as: :deposit_products
      get 'deposits/:id/products/new' => 'deposits#new_product', as: :new_deposit_product
      get 'deposits/:deposit_id/products/:product_id' => 'deposits#show_product', as: :deposit_product
      post 'deposits/:deposit_id/products' => 'deposits#add_product'
      get 'deposits/:deposit_id/products/:product_id/edit' => 'deposits#edit_product', as: :edit_deposit_product
      patch 'deposits/:deposit_id/products/:product_id' => 'deposits#update_product' 
      put 'deposits/:deposit_id/products/:product_id' => 'deposits#update_product' 
      
      get 'stores/:store_id/products' => 'stores#products', as: :store_products
      get 'stores/:store_id/products/new' => 'stores#new_product', as: :new_store_product
      get 'stores/:store_id/products/:product_id' => 'stores#show_product', as: :store_product 
      post 'stores/:store_id/products' => 'stores#add_product'
      get 'stores/:store_id/products/:id/edit' => 'stores#edit_product', as: :edit_store_product
      patch 'stores/:store_id/products/:id' => 'stores#update_product' 
      put 'stores/:store_id/products/:id' => 'stores#update_product' 
      get 'stores/:store_id/close_cash' => 'stores#close_cash', as: :close_cash
      
    end
    resources :loads
    resources :downloads
    resources :sales
    resources :bills
  end
  
  namespace "seller" do
    resources :users
    get 'store/products' => 'stores#products', as: :store_products
    get 'store' => 'stores#show', as: :store
    get 'store/close_cash' => 'stores#close_cash', as: :close_cash
      
    resources :sales
    resources :bills

  end
    resources :users
    resources :products
    resources :categories
    resources :brands
    resources :units

end

app/models/store.rb
class Store < ActiveRecord::Base
	belongs_to :commerce
  	has_many :sellers

  	has_many :downloads

  	has_many :products, through: :downloads

  	has_many :deposits, through: :downloads

	extend FriendlyId
  	friendly_id :nombre, use: :slugged

  	def nombre_comercio
  		self.commerce ? self.commerce.nombre : "S/C"
 	end

 	def products_count
    	self.products.count
  	end
end

app/controllers/admin/stores_controller.rb
class StoresController < ApplicationController
  before_action :set_store, only: [:show, :edit, :update, :destroy]
  before_action :set_commerce, only:[:new_store_of_commerce]

  # GET /stores
  # GET /stores.json
 def index
    if current_user.admin?
      @stores = Store.all
    end
    if current_user.owner?
     @stores=current_user.commerces.friendly.find(get_commerce(params[:commerce_id])).stores
    end
  end

  # GET /stores/1
  # GET /stores/1.json
  def show
  end

  # GET /stores/new
  def new
    if current_user.admin?
      @store = Store.new
    end
    if current_user.owner?
      @commerce = get_commerce(params[:commerce_id])
      @store = Store.new
      @store.commerce_id = @commerce.id
    end
    
  end
  # GET /commerce/:commerce_id/store/new

  # GET /stores/1/edit
  def edit
    if current_user.owner?
      @commerce = get_commerce(params[:commerce_id])
    end
  end

  # POST /stores
  # POST /stores.json
  def create
    @store = Store.new(store_params)

    respond_to do |format|
      if @store.save
        ruta = current_user.admin? ? stores_path : stores_of_commerce_path(@store.commerce.slug)
        puts"RUTA****"+ruta+"******"
        format.html { redirect_to ruta, notice: 'Tienda creada exitosamente.' }
        format.json { render :show, status: :created, location: @store }
      else
        format.html { render :new }
        format.json { render json: @store.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /stores/1
  # PATCH/PUT /stores/1.json
  def update
    respond_to do |format|
      if @store.update(store_params)
        ruta = current_user.admin? ? stores_path : stores_of_commerce_path(@store.commerce.slug)
        format.html { redirect_to ruta, notice: 'Tienda actualizada exitosamente.' }
        format.json { render :show, status: :ok, location: @store }
      else
        format.html { render :edit }
        format.json { render json: @store.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stores/1
  # DELETE /stores/1.json
  def destroy
    @store.destroy
    respond_to do |format|
      format.html { redirect_to stores_url, notice: 'Store was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_store
      @store = Store.friendly.find(params[:id])
    end
    def set_commerce
      if(params[:commerce_id])
        puts "******1**"
        @commerce = Commerce.friendly.find(params[:commerce_id])
        puts @commerce.to_json
        puts "******FIN**"
      end
    end
    # Never trust parameters from the scary internet, only allow the white list through.
    def store_params
      params.require(:store).permit(:nombre, :direccion, :commerce_id)
    end
end

app/controllers/owner/stores_controller.rb
class Owner::StoresController < ApplicationController
  before_action :set_commerce
  before_action :checks, only: [:new_product]
  before_action :set_store, only: [:show, :edit, :update, :destroy,:products,:new_product,:add_product,:close_cash]
  after_action :set_date_created_at, only: [:add_product]
  include ApplicationHelper

  # GET /stores
  # GET /stores.json
  def index
    @stores = @commerce.stores
  end

  # GET /stores/1
  # GET /stores/1.json
  def show
    products()
    bills()
    today_bills()
  end

  # GET /stores/new
  def new
      @store = Store.new
  end
  
  # GET /stores/1/edit
  def edit
  end

  # POST /stores
  # POST /stores.json
  def create
    @store = Store.new(store_params)
    @store.commerce = @commerce
    @seller = Seller.new
    respond_to do |format|
      if @store.save
        @seller.store=@store
        @seller.commerce = @commerce
        @seller.user_id=current_user.id
        @seller.slug=current_user.cedula
        puts "DATOS DE VENDEDOR *******"
        puts @seller.to_json
        @seller.save
        format.html { redirect_to owner_commerce_stores_path(@store.commerce.slug), notice: 'Tienda creada exitosamente.' }
        format.json { render :show, status: :created, location: @store }
      else
        format.html { render :new }
        format.json { render json: @store.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /stores/1
  # PATCH/PUT /stores/1.json
  def update
    respond_to do |format|
      @store.slug=nil
      if @store.update(store_params)
        format.html { redirect_to owner_commerce_stores_path(@store.commerce.slug), notice: 'Tienda actualizado exitosamente.' }
        format.json { render :show, status: :ok, location: @store }
      else
        format.html { render :edit }
        format.json { render json: @store.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stores/1
  # DELETE /stores/1.json
  def destroy
    @store.destroy
    respond_to do |format|
      format.html { redirect_to stores_url, notice: 'Store was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  def products
    puts "INICIO PRODUCTS"
    @products_grouped = @store.downloads.group_by {|download| download.product_id}
    @products = []
    @products_grouped.each do |attr_name, attr_value|
      downloads = Download.where(id: attr_value.map(&:id)).order(:created_at)
      @product = Download.new(product_id: Product.find(attr_name).id, 
                              cantidad: downloads.sum(:cantidad),
                              precio: downloads.last.precio)
      @products.push(@product)
    end
  end
  def bills
    sellers = @store.sellers
    @bills=[]
    sellers.each do|s|
      s.bills.each do|b|
        @bills.push(b)
      end
    end
  end
  def today_bills
    sellers = @store.sellers
    @time = getCurrentTime
    @time = @time ? @time : Date.today
    puts "EPAA"+@time.to_s
    selected_date = Date.parse(@time.to_s)
    @today_bills = []
    sellers.each do|s|
      selected = s.bills.where(:created_at => selected_date.beginning_of_day..selected_date.end_of_day)
      @today_bills += selected
    end
  puts "today_bills::"+@today_bills.to_s
  end
  def close_cash
    today_bills()
    puts "close_cash::"+@today_bills.to_s

    if @today_bills.size>0
      selected_date = Date.parse(@time)
      if current_user.seller.closures.where(:created_at => selected_date.beginning_of_day..selected_date.end_of_day).size==0
        @closure = Closure.new
        @closure.seller=current_user.seller
        @today_bills.each do |b|
          b.closure = @closure
          b.save
        end
        @closure.created_at=@time
        @closure.updated_at=@time
        @closure.save
        fecha = format_date_to_file(Date.parse(@time))
        $pdf = ClosePDF.new("cierre_#{fecha}.pdf",@today_bills,format_date(DateTime.parse(@time)))
        puts "PDF.FILENAME::"+$pdf.file_name
        redirect_to(owner_commerce_store_path(@commerce,@store),notice: "Ventas del dia cerradas exitosamente")
      else
        redirect_to(:back,alert: "Disculpa, ya hiciste tu cierre de ventas del dia")
      end
    else
      redirect_to(:back,alert: "Disculpa, no existen ventas para cerrar")
    end

  end

  def new_product
    commerces=current_user.commerces
    deposits_count=0
    stores_count=0
    products_deposits_count =0
    products_stores_count =0
    commerces.each do |c|
      deposits = c.deposits
      stores = c.stores
      deposits_count += deposits.count
      stores_count += stores.count
      deposits.each do |d|
        products_deposits_count += d.products.count
      end

      stores.each do |s|
       products_stores_count += s.products.count
      end
    end
    puts "Cantidad de comercios::"+commerces.count.to_s
    puts "Cantidad de depositos::"+deposits_count.to_s
    puts "Cantidad de tiendas::"+stores_count.to_s
    puts "Cantidad de productos en deposito::"+products_deposits_count.to_s
    if  commerces.count == 0 or
        deposits_count == 0 or
        stores_count == 0 or
        products_deposits_count == 0 
        redirect_to(:back,alert: "Disculpa, no posees elementos para hacer una descarga.")
    end
        @download = Download.new
    @deposits = @commerce.deposits
  end

  def add_product
    @download = Download.new(download_params)
    @download.cantidad_inicial = @download.cantidad
    @download.store = @store
    if !descarga_valida(@download)
      redirect_to :back, alert: 'No existe la cantidad solicitada en el depósito.'
      return
    end

    respond_to do |format|
      if @download.save
        format.html { redirect_to owner_commerce_store_products_path(@commerce,@store), notice: 'Se agregó el producto a la tienda exitosamente.' }
        format.json { render :show, status: :created, location: @download }
      else
        format.html { render :new }
        format.json { render json: @download.errors, status: :unprocessable_entity }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def checks
      if  Product.all.count == 0
        redirect_to(:back,alert: "Disculpa, debes crear productos primero.")
      end
    end
    def set_date_created_at
      if params[:fecha]
        f = JSON.parse(params[:fecha])
        fecha = DateTime.new(f["anio"], f["mes"], f["dia"],  f["hora"],  f["min"],  f["seg"])
      end
      time = getCurrentTime
      @download.created_at = time ? time : (fecha ? fecha : Date.today)
      @download.updated_at = time ? time : (fecha ? fecha : Date.today)
      @download.save
    end
    def set_store
     @store = @commerce.stores.friendly.find(params[:store_id] ? params[:store_id] : params[:id])
    end
    # Never trust parameters from the scary internet, only allow the white list through.
    def store_params
      params.require(:store).permit(:nombre, :direccion, :commerce_id)
    end
    def download_params
      params.require(:download).permit(:cantidad, :precio,:product_id,:deposit_id)
    end 
end

app/controllers/seller/stores_controller.rb
class Seller::StoresController < ApplicationController
  before_action :set_store, only: [:show, :edit, :update, :destroy,:products,:close_cash]
  include ApplicationHelper

  # GET /stores
  # GET /stores.json
  def index
    @stores = @commerce.stores
  end

  # GET /stores/1
  # GET /stores/1.json
  def show
    products()
    bills()
    today_bills()
  end

  # GET /stores/new
  def new
      @store = Store.new
  end
  
  # GET /stores/1/edit
  def edit
  end

  # POST /stores
  # POST /stores.json
  def create
    @store = Store.new(store_params)
    @store.commerce = @commerce
      
    respond_to do |format|
      if @store.save
        format.html { redirect_to owner_commerce_stores_path(@store.commerce.slug), notice: 'Depósito creado exitosamente.' }
        format.json { render :show, status: :created, location: @store }
      else
        format.html { render :new }
        format.json { render json: @store.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /stores/1
  # PATCH/PUT /stores/1.json
  def update
    respond_to do |format|
      @store.slug=nil
      if @store.update(store_params)
        format.html { redirect_to owner_commerce_stores_path(@store.commerce.slug), notice: 'Depósito actualizado exitosamente.' }
        format.json { render :show, status: :ok, location: @store }
      else
        format.html { render :edit }
        format.json { render json: @store.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stores/1
  # DELETE /stores/1.json
  def destroy
    @store.destroy
    respond_to do |format|
      format.html { redirect_to stores_url, notice: 'Store was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  def products
    @products_grouped = @store.downloads.group_by {|download| download.product_id}
    @products = []
    @products_grouped.each do |attr_name, attr_value|
      downloads = Download.where(id: attr_value.map(&:id)).order(:created_at)
      @product = Download.new(product_id: Product.find(attr_name).id, 
                              cantidad: downloads.sum(:cantidad),
                              precio: downloads.last.precio)
      @products.push(@product)
    end
  end
  def bills
    sellers = @store.sellers
    @bills=[]
    sellers.each do|s|
      s.bills.each do|b|
        @bills.push(b)
      end
    end
  end
  def today_bills
    sellers = @store.sellers
    @time = getCurrentTime
    @time = @time ? @time : Date.today
    puts "EPAA"+@time.to_s
    selected_date = Date.parse(@time)
    @today_bills = []
    sellers.each do|s|
      selected = s.bills.where(:created_at => selected_date.beginning_of_day..selected_date.end_of_day)
      @today_bills += selected
    end
  puts "today_bills::"+@today_bills.to_s
  end
  def close_cash
    today_bills()
    puts "close_cash::"+@today_bills.to_s

    if @today_bills.size>0
      selected_date = Date.parse(@time)
      if current_user.seller.closures.where(:created_at => selected_date.beginning_of_day..selected_date.end_of_day).size==0
        @closure = Closure.new
        @closure.seller=current_user.seller
        @today_bills.each do |b|
          b.closure = @closure
          b.save
        end
        @closure.created_at=@time
        @closure.updated_at=@time
        @closure.save
        fecha = format_date_to_file(Date.parse(@time))
        $pdf = ClosePDF.new("cierre_#{fecha}.pdf",@today_bills,format_date(DateTime.parse(@time)))
        puts "PDF.FILENAME::"+$pdf.file_name
        redirect_to(seller_bills_path,notice: "Ventas del dia cerradas exitosamente")
      else
        redirect_to(:back,alert: "Disculpa, ya hiciste tu cierre de ventas del dia")
      end
    else
      redirect_to(:back,alert: "Disculpa, no existen ventas para cerrar")
    end

  end

 
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_store
     @store = current_user.sellers.first.store
    end
    # Never trust parameters from the scary internet, only allow the white list through.
    def store_params
      params.require(:store).permit(:nombre, :direccion, :commerce_id)
    end
    def download_params
      params.require(:download).permit(:cantidad, :precio,:product_id,:deposit_id)
    end 
end

app/helpers/stores_helper.rb
module StoresHelper
end

app/views/stores/_form.html.erb
<%= form_for(@store) do |f| %>

  <script type="text/javascript">
   var errorsArray=[] ;
  <% @store.errors.each do |atributo, mensaje| %>
      errorsArray.push({atributo:"<%="#{atributo}"%>",mensaje:"<%="#{mensaje}"%>"});
  <% end %>
  $( document ).ready(function() {
    validarErrores(errorsArray);
  });
</script>

  <div class="box box-primary">
    <div class="box-header with-border">
      <h3 class="box-title">Datos de la Tienda</h3>
    </div><!-- /.box-header -->

    <div class="box-body">
      <div class="row">
        <div class="col-xs-12 col-sm-6 col-md-6 col-lg-6">
          <div class="form-group">
            <%= f.label :commerce_id, "Comercio asociado" %><br>

            <%if current_user.admin?%>
              <%= f.select :commerce_id, options_for_select(Commerce.all.pluck(:nombre,:id),( @store.commerce ? @store.store_id : "" )),{},{class:"form-control select2"}%>
            <%end%>

            <%if @commerce!=nil %>
              <%=@commerce.nombre%>
              <%= f.text_field :commerce_id,class:"form-control",type: "hidden" %>
            <%end%>
          </div>
        </div>
      </div>
      <div class="row">
          <div class="col-xs-12 col-sm-6 col-md-6 col-lg-6">
            <div class="form-group">
              <%= f.label :nombre %>*<br>
              <%= f.text_field :nombre,class:"form-control" %>
            </div>
        </div>
      </div>
      <div class="row">
          <div class="col-xs-12 col-sm-6 col-md-6 col-lg-6">
            <div class="form-group">
              <%= f.label :direccion, "Dirección" %><br>
              <%= f.text_area :direccion ,class:"form-control" %>
            </div>
        </div>
      </div>

    </div><!-- /.box-body -->
  </div><!-- /.box -->
  
    <div class="box-footer">
      <%= f.submit "Guardar", class: "visible-xs btn btn-block btn-primary btn-lg" %>
      <%= f.submit "Guardar", class: "hidden-xs btn btn-primary" %>
    </div>
<% end %>


<script>
      $(function () {
        //Initialize Select2 Elements
        $(".select2").select2();
      });
</script>

app/views/stores/_stores_table.html.erb
          <div class="row">
            <div class="col-xs-12">


              <div class="box">
                <div class="box-header">
                  <h3 class="box-title">Lista de Tiendas<%=@commerce ? " de "+@commerce.nombre : "" %></h3>
                </div><!-- /.box-header -->
                <div class="box-body">
                  <table id="stores_table" class="display table table-bordered table-striped" cellspacing="0" width="100%">
                    <thead>
                      <tr>
                        <th>Nombre</th>
                        <%if current_user.admin?%>
                          <th>Comercio</th>
                        <%end%>
                        <th class="hidden-xs">Dirección</th>
                      </tr>
                    </thead>
                    <tbody>
                    <% @stores.each_with_index do |store,index| %>
                      <tr class="link" data-toggle="modal" data-target=<%="#modal-store-"+index.to_s%>>
                        <td><%= store.nombre %></td>
                        <%if current_user.admin?%>
                          <td><%= store.commerce.nombre %></td>
                        <%end%>
                        <td class="hidden-xs"><%= store.direccion %></td>
                      </tr>
                        <div class="example-modal">
                          <div class="modal fade" id=<%="modal-store-"+index.to_s%>>
                            <div class="modal-dialog">
                              <div class="modal-content">
                                <div class="modal-header">
                                  <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                                  <h4 class="modal-title">Información</h4>
                                </div>
                                <div class="modal-body">
                                  <div class="row">
                                    <div class="col-xs-12">
                                      <div class="box box-solid">
                                        <div class="box-header with-border">
                                          <i class="fa fa-text-width"></i>
                                          <h3 class="box-title">Datos de la tienda</h3>
                                        </div><!-- /.box-header -->
                                        <div class="box-body">
                                          <dl>
                                            <dt>Nombre:</dt>
                                            <dd><%=store.nombre%></dd>
                                            <%if current_user.admin?%>
                                            <dt>Comercio:</dt>
                                            <dd><%=store.commerce.nombre%></dd>
                                            <%end%>
                                            <dt>Dirección:</dt>
                                            <dd><%=store.direccion%></dd>
                                                                              
                                          </dl>
                                          <%= link_to 'Ver Productos', products_of_store_path(store), class:"visible-xs btn btn-block btn-warning btn-sm" %>
                                          <%= link_to 'Ver Productos', products_of_store_path(store), class:"hidden-xs btn btn-warning btn-sm" %>
                                       </div><!-- /.box-body -->
                                      </div><!-- /.box -->
                                    </div><!-- ./col -->
                                  </div><!-- /.row -->
                                </div>
                                <div class="modal-footer">
                                  <button type="button" class="btn btn-default pull-left" data-dismiss="modal">Cerrar</button>
                                  
                                  <button data-url=<%=stores_path%> data-id=<%=store.id%> type="button" class="btn btn-danger delete-record">Eliminar</button>
                                  <button type="button" class="btn btn-primary" aria-label="Left Align" onclick="window.location.href='<%=current_user.admin? ? edit_store_path(store) : edit_store_of_commerce_path(@commerce.slug,store) %>'">
                                    <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span> Editar &nbsp;
                                  </button>
                                </div>
                              </div><!-- /.modal-content -->
                            </div><!-- /.modal-dialog -->
                          </div><!-- /.modal -->
                        </div><!-- /.example-modal -->
                      <% end %>
                    </tbody>
                    <tfoot>
                      <tr>
                        <th>Nombre</th>
                        <%if current_user.admin?%>
                          <th>Comercio</th>
                        <%end%>
                        <th class="hidden-xs">Descripción</th>
                      </tr>
                    </tfoot>
                  </table>
                </div><!-- /.box-body -->
              </div><!-- /.box -->
            </div><!-- /.col -->
          </div><!-- /.row -->

app/views/stores/index.html.erb
       <!-- Main content -->
        <section class="content">
          <%= render 'stores_table' %>
        </section><!-- /.content -->


 <script>
      $(function () {
        $("#stores_table").DataTable({
          "language": {
            "url": "/plugins/datatables/dataTables.spanish.lang"
          },
          "columnDefs": [ {
          "targets": 'no-sort',
          "orderable": false,
          "searchable": false
          } ],
          stateSave: true
        });
      });
</script>
<br>


<div class="row">
    <div class="col-xs-1 col-sm-0"> </div>
    <div class="col-xs-10 col-sm-12"> 

<%= link_to 'Nueva  Tienda', current_user.admin? ? new_store_path : new_store_of_commerce_path(@commerce)  ,class:"visible-xs btn btn-block btn-primary btn-lg"%>
<%= link_to 'Nueva  Tienda', current_user.admin? ? new_store_path : new_store_of_commerce_path(@commerce)  ,class:"hidden-xs btn btn-primary "%>


    </div>
    <div class="col-xs-1 col-sm-0"> </div>

</div> 

app/views/stores/new.html.erb
<h1>Nueva Tienda</h1>

<%= render 'form' %>

app/views/stores/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre:</strong>
  <%= @store.nombre %>
</p>

<p>
  <strong>Direccion:</strong>
  <%= @store.direccion %>
</p>

<%= link_to 'Edit', edit_store_path(@store) %> |
<%= link_to 'Back', stores_path %>