config/routes.rb
Rails.application.routes.draw do

  resources :closures

  resources :sessions
  get 'welcome/index'

  get 'login' => 'sessions#new', as: :login
  get 'logout' => 'sessions#destroy', as: :logout

  get 'check_pdf' => 'welcome#check_pending_pdf'
  get 'download' => 'welcome#download'
  

  post 'create_admin_user' => 'welcome#create_admin_user', as: :create_admin_user
  get 'admin_user' => 'welcome#admin_user', as: :administrator_user
  

  

  get 'admin' => 'welcome#admin', as: :admin_index
  get 'owner' => 'welcome#owner', as: :owner_index
  get 'seller' => 'welcome#seller', as: :seller_index

  root 'welcome#index'

  get 'my_profile' => 'users#my_profile', as: :my_profile
  namespace "admin" do
    resources :users
    resources :roles
    resources :commerces
    resources :stores
    resources :deposits
    resources :sellers
    resources :downloads
    resources :loads
  end
  
 
  namespace "owner" do
    resources :users
    resources :commerces do
      resources :deposits, :stores,:sellers
      get 'deposits/:id/products' => 'deposits#products', as: :deposit_products
      get 'deposits/:id/products/new' => 'deposits#new_product', as: :new_deposit_product
      get 'deposits/:deposit_id/products/:product_id' => 'deposits#show_product', as: :deposit_product
      post 'deposits/:deposit_id/products' => 'deposits#add_product'
      get 'deposits/:deposit_id/products/:product_id/edit' => 'deposits#edit_product', as: :edit_deposit_product
      patch 'deposits/:deposit_id/products/:product_id' => 'deposits#update_product' 
      put 'deposits/:deposit_id/products/:product_id' => 'deposits#update_product' 
      
      get 'stores/:store_id/products' => 'stores#products', as: :store_products
      get 'stores/:store_id/products/new' => 'stores#new_product', as: :new_store_product
      get 'stores/:store_id/products/:product_id' => 'stores#show_product', as: :store_product 
      post 'stores/:store_id/products' => 'stores#add_product'
      get 'stores/:store_id/products/:id/edit' => 'stores#edit_product', as: :edit_store_product
      patch 'stores/:store_id/products/:id' => 'stores#update_product' 
      put 'stores/:store_id/products/:id' => 'stores#update_product' 
      get 'stores/:store_id/close_cash' => 'stores#close_cash', as: :close_cash
      
    end
    resources :loads
    resources :downloads
    resources :sales
    resources :bills
  end
  
  namespace "seller" do
    resources :users
    get 'store/products' => 'stores#products', as: :store_products
    get 'store' => 'stores#show', as: :store
    get 'store/close_cash' => 'stores#close_cash', as: :close_cash
      
    resources :sales
    resources :bills

  end
    resources :users
    resources :products
    resources :categories
    resources :brands
    resources :units

end

app/models/unit.rb
class Unit < ActiveRecord::Base
	has_many :products
 	extend FriendlyId
  	friendly_id :nombre, use: :slugged
end

app/controllers/units_controller.rb
class UnitsController < ApplicationController
  before_action :set_unit, only: [:show, :edit, :update, :destroy]

  # GET /units
  # GET /units.json
  def index
    @units = Unit.all
  end

  # GET /units/1
  # GET /units/1.json
  def show
  end

  # GET /units/new
  def new
    @unit = Unit.new
  end

  # GET /units/1/edit
  def edit
  end

  # POST /units
  # POST /units.json
  def create
    @unit = Unit.new(unit_params)

    respond_to do |format|
      if @unit.save
        format.html { redirect_to @unit, notice: 'Unit was successfully created.' }
        format.json { render :show, status: :created, location: @unit }
      else
        format.html { render :new }
        format.json { render json: @unit.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /units/1
  # PATCH/PUT /units/1.json
  def update
    respond_to do |format|
      if @unit.update(unit_params)
        format.html { redirect_to @unit, notice: 'Unit was successfully updated.' }
        format.json { render :show, status: :ok, location: @unit }
      else
        format.html { render :edit }
        format.json { render json: @unit.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /units/1
  # DELETE /units/1.json
  def destroy
    @unit.destroy
    respond_to do |format|
      format.html { redirect_to units_url, notice: 'Unit was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_unit
      @unit = Unit.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def unit_params
      params.require(:unit).permit(:nombre, :abv, :descripcion)
    end
end

app/helpers/units_helper.rb
module UnitsHelper
end

app/views/units/_form.html.erb
<%= form_for(@unit) do |f| %>
  <% if @unit.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@unit.errors.count, "error") %> prohibited this unit from being saved:</h2>

      <ul>
      <% @unit.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nombre %><br>
    <%= f.text_field :nombre %>
  </div>
  <div class="field">
    <%= f.label :abv %><br>
    <%= f.text_field :abv %>
  </div>
  <div class="field">
    <%= f.label :descripcion %><br>
    <%= f.text_area :descripcion %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/units/edit.html.erb
<h1>Editing unit</h1>

<%= render 'form' %>

<%= link_to 'Show', @unit %> |
<%= link_to 'Back', units_path %>

app/views/units/index.html.erb
<h1>Listing units</h1>

<table>
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Abv</th>
      <th>Descripcion</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @units.each do |unit| %>
      <tr>
        <td><%= unit.nombre %></td>
        <td><%= unit.abv %></td>
        <td><%= unit.descripcion %></td>
        <td><%= link_to 'Show', unit %></td>
        <td><%= link_to 'Edit', edit_unit_path(unit) %></td>
        <td><%= link_to 'Destroy', unit, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Unit', new_unit_path %>

app/views/units/new.html.erb
<h1>New unit</h1>

<%= render 'form' %>

<%= link_to 'Back', units_path %>

app/views/units/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre:</strong>
  <%= @unit.nombre %>
</p>

<p>
  <strong>Abv:</strong>
  <%= @unit.abv %>
</p>

<p>
  <strong>Descripcion:</strong>
  <%= @unit.descripcion %>
</p>

<%= link_to 'Edit', edit_unit_path(@unit) %> |
<%= link_to 'Back', units_path %>