config/routes.rb
Rails.application.routes.draw do

  resources :closures

  resources :sessions
  get 'welcome/index'

  get 'login' => 'sessions#new', as: :login
  get 'logout' => 'sessions#destroy', as: :logout

  get 'check_pdf' => 'welcome#check_pending_pdf'
  get 'download' => 'welcome#download'
  

  post 'create_admin_user' => 'welcome#create_admin_user', as: :create_admin_user
  get 'admin_user' => 'welcome#admin_user', as: :administrator_user
  

  

  get 'admin' => 'welcome#admin', as: :admin_index
  get 'owner' => 'welcome#owner', as: :owner_index
  get 'seller' => 'welcome#seller', as: :seller_index

  root 'welcome#index'

  get 'my_profile' => 'users#my_profile', as: :my_profile
  namespace "admin" do
    resources :users
    resources :roles
    resources :commerces
    resources :stores
    resources :deposits
    resources :sellers
    resources :downloads
    resources :loads
  end
  
 
  namespace "owner" do
    resources :users
    resources :commerces do
      resources :deposits, :stores,:sellers
      get 'deposits/:id/products' => 'deposits#products', as: :deposit_products
      get 'deposits/:id/products/new' => 'deposits#new_product', as: :new_deposit_product
      get 'deposits/:deposit_id/products/:product_id' => 'deposits#show_product', as: :deposit_product
      post 'deposits/:deposit_id/products' => 'deposits#add_product'
      get 'deposits/:deposit_id/products/:product_id/edit' => 'deposits#edit_product', as: :edit_deposit_product
      patch 'deposits/:deposit_id/products/:product_id' => 'deposits#update_product' 
      put 'deposits/:deposit_id/products/:product_id' => 'deposits#update_product' 
      
      get 'stores/:store_id/products' => 'stores#products', as: :store_products
      get 'stores/:store_id/products/new' => 'stores#new_product', as: :new_store_product
      get 'stores/:store_id/products/:product_id' => 'stores#show_product', as: :store_product 
      post 'stores/:store_id/products' => 'stores#add_product'
      get 'stores/:store_id/products/:id/edit' => 'stores#edit_product', as: :edit_store_product
      patch 'stores/:store_id/products/:id' => 'stores#update_product' 
      put 'stores/:store_id/products/:id' => 'stores#update_product' 
      get 'stores/:store_id/close_cash' => 'stores#close_cash', as: :close_cash
      
    end
    resources :loads
    resources :downloads
    resources :sales
    resources :bills
  end
  
  namespace "seller" do
    resources :users
    get 'store/products' => 'stores#products', as: :store_products
    get 'store' => 'stores#show', as: :store
    get 'store/close_cash' => 'stores#close_cash', as: :close_cash
      
    resources :sales
    resources :bills

  end
    resources :users
    resources :products
    resources :categories
    resources :brands
    resources :units

end

app/models/category.rb
class Category < ActiveRecord::Base
	has_many :products
	extend FriendlyId
  	friendly_id :nombre, use: :slugged
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to categories_path, notice: 'Categoria creada exitosamente.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to categories_path, notice: 'Categoria actualizada exitosamente.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.friendly.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:nombre, :descripcion)
    end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_form.html.erb
<%= form_for(@category) do |f| %>

  <script type="text/javascript">
   var errorsArray=[] ;
  <% @category.errors.each do |atributo, mensaje| %>
      errorsArray.push({atributo:"<%="#{atributo}"%>",mensaje:"<%="#{mensaje}"%>"});
  <% end %>
  $( document ).ready(function() {
    validarErrores(errorsArray);
  });
</script>

  <div class="box box-primary">
    <div class="box-header with-border">
      <h3 class="box-title">Datos de la Categoría</h3>
    </div><!-- /.box-header -->

    <div class="box-body">
      <div class="row">
          <div class="col-xs-12 col-sm-6 col-md-6 col-lg-6">
            <div class="form-group">
              <%= f.label :nombre %>*<br>
              <%= f.text_field :nombre,class:"form-control" %>
            </div>
        </div>
      </div>
      <div class="row">
          <div class="col-xs-12 col-sm-6 col-md-6 col-lg-6">
            <div class="form-group">
              <%= f.label :descripcion %><br>
              <%= f.text_area :descripcion ,class:"form-control" %>
            </div>
        </div>
      </div>

    </div><!-- /.box-body -->
  </div><!-- /.box -->
  
    <div class="box-footer">
      <%= f.submit "Guardar", class: "visible-xs btn btn-block btn-primary btn-lg" %>
      <%= f.submit "Guardar", class: "hidden-xs btn btn-primary" %>
    </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Actualizar categoría</h1>

<%= render 'form' %>

app/views/categories/index.html.erb
       <!-- Main content -->
        <section class="content">
          <div class="row">
            <div class="col-xs-12">


              <div class="box">
                <div class="box-header">
                  <h3 class="box-title">Lista de Categorías</h3>
                </div><!-- /.box-header -->
                <div class="box-body">
                  <table id="categories_table" class="display table table-bordered table-striped" cellspacing="0" width="100%">
                    <thead>
                      <tr>
                        <th>Nombre</th>
                        <th>Descripción</th>
                      </tr>
                    </thead>
                    <tbody>
                    <% @categories.each_with_index do |category,index| %>
                      <tr class="link" data-toggle="modal" data-target=<%="#modal-category-"+index.to_s%>>
                        <td><%= category.nombre %></td>
                        <td><%= category.descripcion %></td>
                      </tr>
                        <div class="example-modal">
                          <div class="modal fade" id=<%="modal-category-"+index.to_s%>>
                            <div class="modal-dialog">
                              <div class="modal-content">
                                <div class="modal-header">
                                  <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                                  <h4 class="modal-title">Información</h4>
                                </div>
                                <div class="modal-body">
                                  <div class="row">
                                    <div class="col-xs-12">
                                      <div class="box box-solid">
                                        <div class="box-header with-border">
                                          <i class="fa fa-text-width"></i>
                                          <h3 class="box-title">Datos de la categoría</h3>
                                        </div><!-- /.box-header -->
                                        <div class="box-body">
                                          <dl>
                                            <dt>Nombre:</dt>
                                            <dd><%=category.nombre%></dd>
                                            <dt>Descripción:</dt>
                                            <dd><%=category.descripcion%></dd>
                                                                              
                                          </dl>
                                       </div><!-- /.box-body -->
                                      </div><!-- /.box -->
                                    </div><!-- ./col -->
                                  </div><!-- /.row -->
                                </div>
                                <div class="modal-footer">
                                  <button type="button" class="btn btn-default pull-left" data-dismiss="modal">Cerrar</button>
                                  
                                  <button data-url=<%=categories_path%> data-id=<%=category.id%> type="button" class="btn btn-danger delete-record">Eliminar</button>
                                  <button type="button" class="btn btn-primary" aria-label="Left Align" onclick="window.location.href='<%=edit_category_path(category)%>'">
                                    <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span> Editar &nbsp;
                                  </button>
                                </div>
                              </div><!-- /.modal-content -->
                            </div><!-- /.modal-dialog -->
                          </div><!-- /.modal -->
                        </div><!-- /.example-modal -->
                      <% end %>
                    </tbody>
                    <tfoot>
                      <tr>
                        <th>Nombre</th>
                        <th>Descripción</th>
                      </tr>
                    </tfoot>
                  </table>
                </div><!-- /.box-body -->
              </div><!-- /.box -->
            </div><!-- /.col -->
          </div><!-- /.row -->
        </section><!-- /.content -->


 <script>
      $(function () {
        $("#categories_table").DataTable({
          "language": {
            "url": "/plugins/datatables/dataTables.spanish.lang"
          },
          "columnDefs": [ {
          "targets": 'no-sort',
          "orderable": false,
          "searchable": false
          } ],
          stateSave: true
        });
      });
</script>
<br>

<%= link_to 'Nueva  categoría', new_category_path ,class:"visible-xs btn btn-block btn-primary btn-lg"%>
<%= link_to 'Nueva  categoría', new_category_path ,class:"hidden-xs btn btn-primary "%>

app/views/categories/new.html.erb
<h1>Nueva Categoría</h1>

<%= render 'form' %>

app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre:</strong>
  <%= @category.nombre %>
</p>

<p>
  <strong>Descripcion:</strong>
  <%= @category.descripcion %>
</p>

<%= link_to 'Edit', edit_category_path(@category) %> |
<%= link_to 'Back', categories_path %>